[package]
name = "aux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
json = "0.12.4"
stellar-strkey = "0.0.6"
